### ISSUE TITLE
Enhance PersistenceUtil to allow initialization

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#104]
Hello,

at the moment the <tt>javax.persistence.PersistenceUtil</tt> provides methods to determine the load state of an entity. It would be also nice if we had methods to initialize and unproxy if the entity is a proxy object. I know Hibernate already have this in the <tt>org.hibernate.Hibernate</tt> class. It would be nice to have a pure JPA solution.

**Comment by gavinking** [comment]
This would be good and _very_ easy to add.

**Comment by gavinking** [comment]
Please review proposal #447, which addresses this issue, along with other "missing" functionality of `PersistenceUnitUtil`.
