### ISSUE TITLE
Clarify semantics of BindableType

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#106]
<tt>BindableType</tt> has three values <tt>SINGULAR_ATTRIBUTE</tt>, <tt>PLURAL_ATTRIBUTE</tt>, <tt>ENTITY_TYPE</tt>.

For an entity like this:

```
class User {

  private User manager;
}
```

The lookup of the bindable type for the <tt>manager</tt> property returns <tt>ENTITY_TYPE</tt> on Hibernate and <tt>SINGULAR_ATTRIBUTE</tt> on EclipseLink. I'd argue the latter is wrong as the existence of <tt>ENTITY_TYPE</tt> indicates that it should be preferred over <tt>SINGULAR_ATTRIBUTE</tt> if the attribute indeed is a JPA entity. The spec however is completely silent on this and doesn't define any strict rules.

**Comment by m-reza-rahman** [comment]
This seems like low-hanging fruit that could be looked at in the next release and resolved one way or the other? It does appear to be a fairly low priority either way.

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.

**Comment by gavinking** [comment]
So, okay, this was indeed very slightly ambiguous, though I note that Hibernate already fixed the indicated inconsistency, probably long ago. Anyway, I've "fixed" this issue in #468 by adding some `@see` annotations to the Javadoc.
