### ISSUE TITLE
Lift requirement that MappedSuperclass, Entity and Embeddable classes must be top-level classes

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#110]
Currently, JPA Specification 2.1, section 2.1, paragraph 3, states:

> The entity class must be a top-level class

The section on @Embeddable classes, in turn, refers to that section.
It is my assumption that it would be quite safe also to allow static nested classes without posing too much problems to implementations.
So, I suggest to lift that requirement such that static nested classes are allowed as entities and/or embeddables.
#### Environment
all

**Comment by gavinking** [comment]
This is being done as part of #380. So this issue could be closed.
