### ISSUE TITLE
EntityGraph addAttributeNodes generic type incorrect

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#112]
The method in EntityGraph (and EntitySubgraph)
public void addAttributeNodes(Attribute<T, ?>... attribute);

should be
public void addAttributeNodes(Attribute<? super T, ?>... attribute);

since we should be able to write code like this

EntityGraph<SubEntity> graph = em.createEntityGraph(SubEntity.class);
graph.addAttributeNodes(SubEntity_.baseEntityField);

yet currently it is a compiler error due to this generic type bug.

The same applies to other methods that refer to Attribute<T, ?>

**Comment by andrew-simmons** [comment]
I would suggest that you make T an upper bound:
`public void addAttributeNodes(Attribute<? super T, ?>... attribute);`

My team ran into this issue with a MappedSuperClass that is inherited by two Entities. We would like to consolidate more code that can be shared, but losing the ability to write type safe entity graphs with generated metamodel classes is a show stopper.
