### ISSUE TITLE
Allow full configuration of EntityManagerFactory without persistence.xml

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#114]
I'd like to be able to register classes, set a persistence provider, and also add packages to scan (bonus).

In addition, I don't think persistence unit name should be required-at least an exception shouldn't be thrown if no persistence.xml is found or no persistence unit with the name is found.

My end-goal is an hk2 factory, in the JAX-RS context ([https://jersey.java.net/documentation/latest/ioc.html](https://jersey.java.net/documentation/latest/ioc.html)) that can be instantiated with a JDBC url, username, password, and package names to scan, and then bound to EntityManager for injection. Without the ability to configure the classes that an entity manager factory loads, this is difficult (requires a persistence xml in the project that uses the factory)

**Comment by m-reza-rahman** [comment]
I think this needs a bit more justification. Isn't the JPA SPI doing all this for example for the Spring world? Maybe this should just be closed to reduce clutter or marked as very low priority so the focus can be on higher impact work?

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.

**Comment by gavinking** [comment]
This was done by #465.
