### ISSUE TITLE
remove raw types from JPA API

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#116]
goal is for the API to compile cleanly but the key requirement is for API to remain backward compatible
#### Affected Versions
[2.2]

**Comment by gavinking** [comment]
Done in #487, hope I didn't miss anything.

Note that `Query.getResultStream()` and `Query.getResultList()` have to remain raw for back compatibility.

**Comment by lukasj** [comment]
> Note that Query.getResultStream() and Query.getResultList() have to remain raw for back compatibility.

I've added `@SuppressWarnings({"rawtypes"}` through one commit in #497 - in this particular case it makes sense to have it there
