### ISSUE TITLE
Clarify effect of entity graph on collections

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#125]
The JPA 2.1 spec does not define the effect of an entity graph on the fetch strategy or the result set of a query.

In current TCK compliant implementations, entity graphs may lead to false duplicates due to inappropriate joins.

This is related to #124.

Suppose there is a Person with two addresses and two phone numbers.

Then using an EntityGraph with <tt>addresses</tt> and <tt>phoneNumbers</tt> on the query

```
select p from Person where p.id = 1
```

may return a Person entity with 4 addresses or 4 phoneNumbers, if the implementation fetches the associations via joins.
#### Affected Versions
[2.1.1]

**Comment by gavinking** [comment]
This is just a straight dupe of #124.
