### ISSUE TITLE
Support JOIN/ON for two root entities

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#128]
Currently JPA does not allow root entities after various JOIN clauses which means that especially outer joins cannot be specified and executed without association path. In some cases it may be beneficial when we can join even when the relation is not mapped, e.g. to avoid potentially EAGER One- or @ManyToOne relationship (LAZY is only hint, not guaranteed).

EclispeLink currently supports such joins and they add a lot of options how to solve some problems with a minimal JPQL change. "EclipseLink also supports usage of the ON clause between two root level objects." See: [https://wiki.eclipse.org/EclipseLink/UserGuide/JPA/Basic_JPA_Development/Querying/JPQL#ON](https://wiki.eclipse.org/EclipseLink/UserGuide/JPA/Basic_JPA_Development/Querying/JPQL#ON)

Please, consider root entites as candidates for joins.

**Comment by gavinking** [comment]
To be clear, we're talking about queries like this:

```sql
select book.title, publisher.name
from Book book
    join Publisher publisher
        on book.publisher = publisher
where book.title like :titlePattern
```

Correct?

If so, then this is something that both EclipseLink and Hibernate have supported for quite a long time, and it's something that should be quite trivial to add to the spec.

I would say we can easily do this for 3.2.
