### ISSUE TITLE
Allow defining null handling for ORDER BY expressions in JPQL and the Criteria API

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#130]
Currently, neither JPQL nor the Criteria API allow defining how to handle null values in ORDER BY expressions. All major persistence providers support those clauses though, which makes it sort of usable through JPQL (as the provider might allow the custom extensions) but not through the Criteria API.
#### Affected Versions
[2.1.1]

**Comment by gavinking** [comment]
dupe of #76, fixed by #440.
