### ISSUE TITLE
Make TABLE-generated IDs available on PrePersist

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#133]
JSR-338/3.5.3 states that

> Generated primary key values are available in the <tt>PostPersist</tt> method.

It'll be much helpful if those ids whose <tt>strategy</tt> is <tt>GenerationType.TABLE</tt> are available on <tt>PrePersist</tt>.

exempli gratia

```java
public class MyEntity {

    @PrePersist
    private void onPrePersist() {
        // generate a unique and unchangable value from *available* id.
        derived = String.format("%1$016x", id);
    }

    @GeneratedValue(..., strategy = GenerationType.TABLE)
    @Id
    private Long id;

    @Basic(optional = false)
    @Colum(..., nullable = false, updatable = false)
    @NotNull
    private String derived;
}
```

Note that the <tt>derived</tt> column is not null and not updatable.

**Comment by gavinking** [comment]
This is a pretty reasonable and useful request, it seems to me, and to be honest I'm not sure why Hibernate didn't already do things this way (I guess nobody ever asked us directly). But anyway, looks like I've been able to get that working with a very straightforward change. So from our side I don't think we would have a problem adding it to the spec.

@lukasj WDYT? What does EclipseLink do here?

**Comment by gavinking** [comment]
I have proposed #488. Let's see if other implementors object.

**Comment by lukasj** [comment]
EclipseLink already supports this

**Comment by gavinking** [comment]
OK, so I checked with the Hibernate team and they do not object to the change.
