### ISSUE TITLE
Custom sequence generator

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#143]
Sometimes the application has an application specific strategy for generating ids. Some JPA products provide additional sequencing and id generation options, and configuration hooks.
EclipseLink has org.eclipse.persistence.sequencing.Sequence
[http://wiki.eclipse.org/EclipseLink/Examples/JPA/CustomSequencing](http://wiki.eclipse.org/EclipseLink/Examples/JPA/CustomSequencing)
Hibernate has org.hibernate.id.SequenceGenerator
[https://docs.jboss.org/hibernate/orm/5.2/javadocs/org/hibernate/id/IdentifierGenerator.html](https://docs.jboss.org/hibernate/orm/5.2/javadocs/org/hibernate/id/IdentifierGenerator.html)
DataNucleus
www.datanucleus.org/products/datanucleus/jpa/value_generation.htm
OpenJPA
[https://openjpa.apache.org/builds/2.4.2/apache-openjpa/docs/ref_guide_pc_oid.html](https://openjpa.apache.org/builds/2.4.2/apache-openjpa/docs/ref_guide_pc_oid.html)

All of them trying to supply this lack of functionality not found in the JPA SPEC.
Would you guys consider to include this feature in the upcoming release?
Thanks a lot!
#### Affected Versions
[2.2, 2.1.1]

**Comment by gavinking** [comment]
This old issue does not actually propose any specific functionality. There's at least one other issue (#342) which already asks for support for custom id generators. Closing.
