### ISSUE TITLE
Simplify programmatic bootstrapping of an EntityManagerFactory

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#149]
Currently, I find it incredibly hard to bootstrap an EntityManagerFactory outside of a container. There are tons of blog posts out there who give advice on how to use `PersistenceUnitInfo` et al. to do that, but whenever I try these approaches, I'm wasting hours until I finally give up and resort to using some Spring utilities. This is how I can do it with Spring:

```java
LocalContainerEntityManagerFactoryBean bean = new LocalContainerEntityManagerFactoryBean();
HibernateJpaVendorAdapter adapter = new HibernateJpaVendorAdapter();
adapter.setDatabasePlatform(SQLDialect.H2.thirdParty().hibernateDialect());
bean.setDataSource(new SingleConnectionDataSource(connection, true)); // pre-existing
bean.setPackagesToScan("org.jooq.example.jpa.entity"); // pre-existing
bean.setJpaVendorAdapter(adapter);
bean.setPersistenceUnitName("test");
bean.setPersistenceProviderClass(HibernatePersistenceProvider.class);
bean.afterPropertiesSet();

EntityManagerFactory emf = bean.getObject();
```

Observe that I have:

- A pre-existing `DataSource` or JDBC `Connection` (that's important, and cannot be done through `persistence.xml`)
- Pre-existing entities

That's it. I'm sure this can be done in an even simpler fashion in Spring, or, e.g. through `javax.persistence.Persistence` in a future JPA version.

Hope this helps

**Comment by gavinking** [comment]
Similar issues: #358, #114
