### ISSUE TITLE
Define requirement of using TransactionSynchronizationRegistry in EE environment

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#150]
Currently not all providers integrates with TransactionSynchronizationRegistry - this should be made mandatory in the spec with a fallback to current integration with TransactionManager in environments which do not provide TransactionSynchronizationRegistry.

see also: https://javaee.groups.io/g/jpa-spec/topic/5414652

**Comment by gavinking** [comment]
@lukasj @scottmarlow is this issue still relevant?

**Comment by scottmarlow** [comment]
@gavinking I think we can close this issue as it is already covered well enough in https://jakarta.ee/specifications/platform/10/jakarta-platform-spec-10.0#a1376

**Comment by gavinking** [comment]
OK, thanks. I'll close it. Cheers.
