### ISSUE TITLE
suggest new annotation columnDefine

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#153]
new annotation like this:

	@ColumnDefine(name = "remark",comment="",dialect=MySQL5InnoDBDialect.class,define=JDBCType.xxx,defaultValue=Defaults.xxx,size=32,scale=2)
	private String remark;
Attributes:
	1)dialect
		dialect can be auto regiested by @Dialect 

		@Dialect
		public class MySQL5InnoDBDialect{

		}
	2)define 
                      value from java.sql.JDBCType
	3)defaultValue
                      value from Enum Defaults
		
		enum Defaults{
			NULL,EMPTY_STRING,TRUE,FALSE,ZERO,DATE,TIME,DATETIME,TIME_STAMP;
		}

**Comment by gavinking** [comment]
We should close this issue, since it fails to either:

- state a problem, or
- explain the proposed solution.

And because it's six years old with zero positive feedback.
