### ISSUE TITLE
move CriteriaQuery#getParameters() to CommonAbstractCriteria

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#155]
I'd suggest moving the CriteriaQuery#getParameters() method to the CommonAbstractCriteria interface because parameters may be used on the CriteriaUpdate and the CriteriaDelete criterias as well on the common CriteriaQuery.

So I think we should have the same method on the all criteria types to get assigned parameters.

**Comment by gavinking** [comment]
Fixed by #441.
