### ISSUE TITLE
NullPointerException in AttributeConverter using CDI @Injection 

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#161]
I'm trying to use CDI Injection inside an AttributeConverter but without success the value o the reference converter is allways null. 

At this point I'm using Glassfish 5.0 and the AttributeConverter is the following:

```
import javax.inject.Inject;
import javax.persistence.AttributeConverter;
import java.util.Currency;


@javax.persistence.Converter(autoApply = true)
public class CurrencyAttributeConverter implements AttributeConverter<Currency, String> {

    @Inject
    CurrencyConverter converter;

    @Override
    public String convertToDatabaseColumn(Currency attribute) {
        return converter.to(attribute);
    }

    @Override
    public Currency convertToEntityAttribute(String dbData) {
        return this.converter.from(dbData);
    }
}
```

**Comment by gavinking** [comment]
I don't understand how this is an issue with the JPA spec.

Can we just close it?

**Comment by gavinking** [comment]
Spec section 3.8 says quite explicitly that this is supported:

> Attribute converter classes in Jakarta EE environments support dependency injection through the Contexts and Dependency Injection API (CDI) [7] when CDI is enabled[49]. An attribute converter class that makes use of CDI injection may also define lifecycle callback methods annotated with the PostConstruct and PreDestroy annotations. These methods will be invoked after injection has taken place and before the attribute converter instance is destroyed respectively.
>
> The persistence provider is responsible for using the CDI SPI to create instances of the attribute converter class; to perform injection upon such instances; to invoke their PostConstruct and PreDestroy methods, if any; and to dispose of the attribute converter instances.
>
> The persistence provider is only required to support CDI injection into attribute converters in Jakarta EE container environments[50]. If CDI is not enabled, the persistence provider must not invoke attribute converters that depend upon CDI injection.

... and lots more details.

So there's nothing to do here.
