### ISSUE TITLE
Support for java.time.Instant

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#163]
Original issue #63 mentioned support for java.time.Instant but it's missing in the final 2.2 spec. I haven't found any reason for omitting it.

I feel it's important for supporting pure UTC data flow as described in the #156. Instant already stores epoch internally so it cleanly maps to a UTC timestamp and it would simplify such use case rather than converting back and forth between different (application, database, user) time zones.

I believe that Instant as a [machine-timeline view](http://blog.joda.org/2009/11/why-jsr-310-isn-joda-time_4941.html) should be the recommended approach for persisting time data over LocalDateTime, OffsetDateTime, ZonedDateTime which are human-timeline views.

Hibernate [supports Instant](http://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#basic-datetime) just fine already and allows changing the database timezone via hibernate.jdbc.time_zone.

**Comment by sergeykad** [comment]
@psyklopz Unfortunately this approach does not work correctly with all databases. On Microsoft SQL Server for example you will get local time instead of UTC.

**Comment by psyklopz** [comment]
@sergeykad Great point.  By convention all our servers are set to UTC.  When running on a local dev machine, we pass the time zone (UTC) as part of our connection string to the MySQL JDBC driver.  

Maybe I worry more than I should, but I don't trust that time zone conversions done in Java are always consistent with those done in the database.  

I also get uncomfortable that converting from UTC to local and back to UTC is not foolproof.  In the hour before (or after) daylight savings we have a wrinkle in time.

I wish do had no concept of time zones.  That belongs in the presentation layer and not in the business layers.  But I digress...

Use my sample code if and only if your database and your Java code are both running in UTC.

**Comment by sharmasourabh** [comment]
I am in favor of adding support for Instant to JPA specs.

**Comment by gavinking** [comment]
@lukasj I agree that we should totally do this.

**Comment by gavinking** [comment]
I've proposed support for `Instant` and `Year` in https://github.com/jakartaee/persistence/pull/434.

Note that it's clear why `Instant` was left out of previous revisions of JPA: the JDBC spec does not mention it in Appendix B. But in fact there are other missing type mappings in the JDBC spec, so what I've done is also nailed down the missing type mappings.

**Comment by ritonglue** [comment]
Store `Instant` as a `Long` with and `AttributeConverter<Instant, Long>` using `Instant#getEpochSecond` or `Instant#toEpochMilli`. The only problem you get is when you query directly from the database : you have to convert the long to something that is human readable.
