### ISSUE TITLE
static metamodel for multiple persistence units

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#165]
About generated static metamodel, for example,

```java
@Entity
public class Foo {
    private Long id;
}

@StaticMetamodel(...)
public class Foo_ {

    public static volatile SingleAttribute<Foo, Long> id;

}
```

If the entity class Foo is in multiple persistence units(each persistence unit has a Metamodel), each Metamodel has a different ManagedType instance for the Foo class. which metamodel does the static attributes (e.g. id in the example) belong? Each attribute has method getDeclaringType() which returns ManagedType instance that is persistence unit specific.

**Comment by gavinking** [comment]
I can't imagine what a fix for this situation could possibly look like.

The simple answer is that if you have the same set of entities shared between multiple persistence units then either:

1. put them on different classloaders, or
2. don't use the static metamodel.

There's no non-awful third possibility, is there?

At least this issue report doesn't propose one.

Closing.
