### ISSUE TITLE
Issue with AttributeConverter while retrieving the value using JPQL IN operator

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#168]
Hi,

I have implemented AttributeConverter to store list values into single string column with comma separated. It is working fine except retrieving the records using IN operator in JPQL query like below:

"? in userIds "

Converter Class:

public class ListNumbersConverter implements AttributeConverter<List<Long>, String>

Field in Entity class:

@Column(name = "user_ids", nullable = false)
@Convert(converter = ListNumbersConverter.class)
private List<Long> userIds;

With this I can get only if input param is first element in db value. e.g : DB value is "1,2,3". I am able to retrieve this record if input param value is 1 for above mentioned query, but not able to retrieve if value is either 2 or 3. Could you please guide me how to fix this? Database is MySQL.

**Comment by gavinking** [comment]
> Could you please guide me how to fix this? Database is MySQL.

This sounds like a usage question, not an issue for the JPA specification.

Closing.
