### ISSUE TITLE
Add some constraints for the interpretation JPQL with non entity resultClass

### ISSUE THREAD

**Issue by schauder** [jakartaee/persistence#177]
The specification currently says about `createQuery(String qlString, Class<T> resultClass);` and other similar methods:

> The semantics of this method may be extended in a future release of this specification to support other result types. Applications that specify other result types (e.g., `Tuple.class`) will not be portable.

I wonder if it would be possible to specify at least some constraints for the mapping.

Something like: 
> The query must return the same number of elements as it would if a matching entity type would have been provided or exit with an exception.

While I consider this rather sensible.
Others seem to disagree: https://hibernate.atlassian.net/browse/HHH-12489

**Comment by bukajsytlos** [comment]
upvote

**Comment by gavinking** [comment]
Closing this for similar reasons to #327.
