### ISSUE TITLE
Clarify semantics of including entities in select list

### ISSUE THREAD

**Issue by schauder** [jakartaee/persistence#189]
As discussed in https://hibernate.atlassian.net/browse/HHH-12999 there is room of interpretation for the semantics of queries selecting multiple elements of which one is an entity.

Given two entities `Parent` and `Child` with a one-to-one relationship from `Parent` to `Child`
And two entries in the database for parent, one with child, one without child. What should the following queries return?

    select p.id, p.child from Parent p

1. just one row: the parent that references a child and the child.
2. two rows. One as described in a) and another one with the other parent and a `null` value for the second column.

I think it should be 2. since adding an attribute to a select list (`child`) shouldn't change the number of rows returned and both `select p.id, p.child.id from Parent p` and `select p.id from Parent p` return two rows in Hibernate and in EclipsLink and rightly do so.

Also, please clarify that/if the same number of result is to expected for a query that gets constructed as a Criteria Query:

    CriteriaQuery<Projection> cq = cb.createQuery(Projection.class);
    Root<Parent> parentRoot = cq.from(Parent.class);
    cq.multiselect(parentRoot.get("id"), parentRoot.get("child"));
    TypedQuery<Projection> typedQuery = s.createQuery(cq);
    result = typedQuery.getResultList();

Where `Projection` is a class with two fields, one for the parent-id, one for the child.

And also this one, using `Tuple` as a return type.

    CriteriaQuery<Tuple> cq = cb.createQuery(Tuple.class);
    Root<Parent> parentRoot = cq.from(Parent.class);
    cq.multiselect(parentRoot.get("id"), parentRoot.get("child"));
    TypedQuery<Tuple> typedQuery = s.createQuery(cq);
    return typedQuery.getResultList();

https://github.com/schauder/issue-HHH-12999-superfluous-join demonstrates the queries against Hibernate using the Hibernate API but the transfer to the JPA API is trivial.

The origin of this discussion is an issue on Spring Data JPA: https://jira.spring.io/browse/DATAJPA-1418

**Comment by andyjefferson** [comment]
FWIW DataNucleus JPA follows what to us is the only logical route ... path "2", returning 2 rows. Criteria should always give consistent results to JPQL, and hence it also gives 2 rows using Criteria.

**Comment by gavinking** [comment]
Closing this for similar reasons to #327 and #177.
