### ISSUE TITLE
[JPQL] Support custom functions in joins

### ISSUE THREAD

**Issue by cnsgithub** [jakartaee/persistence#213]
Invocations of custom functions are currently not supported in join paths.

What I would like to do is something like this (currently I am getting an syntax exception what is fine regarding to the spec not supporting it):

````jpql
select e from entity e join function('tableValuedFunction', <param1>, ..., <paramN>) tvf on tvf.col=e.field
````

In SQL Server nomenclature, _table-valued functions_ return a table object which can be joined as it was a regular table, see [How to: Use Table-Valued User-Defined Functions
](https://docs.microsoft.com/de-de/dotnet/framework/data/adonet/sql/linq/how-to-use-table-valued-user-defined-functions)

Other RDBMS provide similar constructs, e.g. [Oracle table functions](https://oracle-base.com/articles/misc/pipelined-table-functions) or [PostgreSQL table functions](https://www.postgresql.org/docs/7.3/xfunc-tablefunctions.html).

My concrete use case is to overcome a SQL Server issue limiting the number of allowed prepared statement parameters to 2100. One of my workarounds worked very well without JPQL and was to provide an user-defined, table-valued function which takes an comma-separated string as input parameter and tokenizes the string by using a delimiter. That way, I need only one parameter to filter more than 2100 values for example:

TSQL:
````sql
create function [tokenize](@str nvarchar(max), @delim char(1) = ',') returns @tokens table (token nvarchar(max))
begin
 declare @i bigint 
 while len(@str) > 0
 begin
  set @i = charindex(@delim, @str)
  insert into @tokens select case @i when 0 then @str else left(@str, @i - 1) end
  set @str = case @i when 0 then '' else right(@str, len(@str) - @i) end
 end
 return
end
go

select * from tokenize('a,b,c', ',')

token
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
a
b
c

(3 rows affected)
````

I would like you to think about it, if it is worth to be supported in JPQL?

**Comment by dazey3** [comment]
Are you referring to JPA 2.2, section [4.6.17.3](https://download.oracle.com/otn-pub/jcp/persistence-2_2-mrel-spec/JavaPersistence.pdf?AuthParam=1557263544_c8e8a95a23f48f8e83391417d318df0f#G4.1537047)?

**Comment by cnsgithub** [comment]
> Are you referring to JPA 2.2, section [4.6.17.3](https://download.oracle.com/otn-pub/jcp/persistence-2_2-mrel-spec/JavaPersistence.pdf?AuthParam=1557263544_c8e8a95a23f48f8e83391417d318df0f#G4.1537047), but being able to declare this as a _join_association_path_expression_?

Yes, exactly.

**Comment by gavinking** [comment]
I don't see how this proposal makes sense.

We don't support joins to *tables* in HQL, and it's entirely unclear what the semantics of that would be. We support joins to *JPA entities*.

Furthermore, this seems to be a very clear example of a query that is easily written in native SQL and executed via `createNativeQuery()`.

So it seems to me that this issue should be closed.

**Comment by beikov** [comment]
Unless we consider representing the result type of table valued functions as entities/embeddables, which I think is nice.

**Comment by gavinking** [comment]
This issue has no votes. I believe that no JPA implementations support it. And I don't believe it makes sense to mix native SQL and JPQL in this fashion. Closing.
