### ISSUE TITLE
JPA Schema generation spec with update

### ISSUE THREAD

**Issue by surapuramakhil** [jakartaee/persistence#235]
Hie,

currently, JPA specification doesn't contain "update" as part of schema generation which is quite useful in maintaining DB schema in sync with the entity classes.

**Comment by gavinking** [comment]
This is a feature that's very difficult to implement in a robust way, and so I don't believe it belongs in the JPA spec.

I think this issue could be closed.

**Comment by gavinking** [comment]
@lukasj WDYT, can we close it?

**Comment by gavinking** [comment]
Actually this issue is a dupe of #68.

@lukasj and I discussed this issue earlier today and we agreed that, while `validate` is probably worth adding, `update` is not.

So I'm going to close this.
