### ISSUE TITLE
Support for the Hibernate specific annotation OptimisticLock

### ISSUE THREAD

**Issue by rainerschamm** [jakartaee/persistence#265]
I would like to propose that this (Hibernate) annotation becomes part of the official JPA spec.

`
@OptimisticLock(excluded = true)
`

Docs:
[https://docs.jboss.org/hibernate/orm/5.4/javadocs/org/hibernate/annotations/OptimisticLock.html](url)

It would greatly improve the versatility of the existing optimistic locking functionality, since the developer would have much more fine grained control over which fields trigger an entity version increment.

**Comment by rbygrave** [comment]
Isn't this a duplicate of https://github.com/eclipse-ee4j/jpa-api/issues/230 ?

**Comment by rainerschamm** [comment]
Oh yea, sorry. I completely forgot about this. To be honest I only remember requesting this on the mailing list at the time.
Please merge or delete.

**Comment by gavinking** [comment]
Either this issue of #230 should be closed.
