### ISSUE TITLE
@AttributeOverride with @Convert optional parameter

### ISSUE THREAD

**Issue by IQbrod** [jakartaee/persistence#292]
@AttributeOverride allow to override database column to reference a new column but does not allow type transformation that might be applied with @Convert for instance.  
My [StackOverflow question](https://stackoverflow.com/questions/63919475/attributeoverride-mappedsuperclass-attribute-with-a-different-type) provides a minimal reproductible example.  
What my child class should/may look like :
```java
@Entity
@Table(name = "flow_catcher")
@AttributeOverride(name = "type", column = @Column(name = "message_type"))
@AttributeOverride(name = "message", column = @Column(name = "count"), @Convert(converter = MyConverter.class))
public class FlowCatcher extends Log {

}
```

My Database column `count` is overriding `message` but the compiler throws the following error :

> Unable to build Hibernate SessionFactory; nested exception is
org.hibernate.tool.schema.spi.SchemaManagementException:
    Schema-validation: wrong column type encountered in column [count] in table [flow_catcher];
    found [int (Types#INTEGER)], but expecting [varchar(255) (Types#VARCHAR)]

And there is no clean way to fix this at the moment. Allowing developpers to provide a @Convert through the @AttributeOverride might fix the problem.

**Comment by gavinking** [comment]
Unless I'm missing something, there's an example (Example 11) of how to do this in section 11.1.10 of the spec and in the Javadoc of the `@Convert` annotation.

You're permitted to write:

```java
@Entity
@Table(name = "flow_catcher")
@AttributeOverride(name = "type", column = @Column(name = "message_type"))
@AttributeOverride(name = "message", column = @Column(name = "count"))
@Convert(attributeName = "message", converter = MyConverter.class)
public class FlowCatcher extends Log {

}
```

I'm going to close this issue, since the requested functionality has been there since JPA 2.1.
