### ISSUE TITLE
EntityManager#find don't support multiple query hints

### ISSUE THREAD

**Issue by MelleD** [jakartaee/persistence#306]
Currently there is no way to execute the EntityManager e.g. entityManager#find 
with multiple query hints with the same keys because a Java map is expected.
There are providers like EclipseLink that support query hints with the same keys.

**Comment by andyjefferson** [comment]
Or maybe the JPA provider should just redesign its "hints" to match the API. 
If someone wants to provide hint "A" as "1" and also hint "A" as "2", they're using some implied logic that the first value is not overridden by the second. If a provider really wants a "hint" to take in multiple values they could use a comma separated value for example, and that way no API change is needed, and its sane.

**Comment by MelleD** [comment]
I opened a ticket at the provider side, I hope we can find a good solution to this issue together.
https://github.com/eclipse-ee4j/eclipselink/issues/1070

**Comment by gavinking** [comment]
IMO, this issue should be closed. I don't think there's any problem here which needs fixing on the JPA side.
