### ISSUE TITLE
JPQL replace() function

### ISSUE THREAD

**Issue by gavinking** [jakartaee/persistence#318]
According to my calculations, all major databases support the `replace()` function, except for Sybase ASE, which has a similar function named `str_replace()`, and Derby.

I think it would be useful to add it to the spec. The signature would be `String replace(String string, String pattern, String replacement)`.

**Comment by gavinking** [comment]
Again, I'm volunteering to write up the spec for this.

**Comment by m-reza-rahman** [comment]
I think it is best for Jakarta Persistence to be relatively conservative on what SQL syntax makes it into the specification. In my experience, this sort of functionality really isn’t needed at the query layer and could/should be done in Java instead, leaving the Jakarta Persistence syntax relatively simple.

**Comment by beikov** [comment]
It seems you don't really use the querying features @m-reza-rahman, but I can tell you, many others are, and having a standard for the querying features is definitely desirable.

**Comment by m-reza-rahman** [comment]
It is fair to say I try to keep my Jakarta Persistence queries simple. I have used the specification since the EJB 2.x Entity Beans days across many, many applications and still develop with it today and have exposure to many customer applications.

 I think we should be cautious about making and stating personal assumptions and remarks. Let’s stick to technical points kindly and remain respectful of differing perspectives and experiences. It would have been sufficient for example to simply state that your experience differs instead of attempting a needless personal value judgement.

**Comment by beikov** [comment]
>I think we should be cautious about making and stating personal assumptions and remarks. Let’s stick to technical points kindly and remain respectful of differing perspectives and experiences. It would have been sufficient for example to simply state that your experience differs instead of attempting a needless personal value judgement.

I didn't mean to offend you. I was trying to say that there are people out there that make extensive use of this and all JPA providers support this function and many others already, so why not standardize it if Gavin is willing do it?

**Comment by gavinking** [comment]
@m-reza-rahman You might indeed have some experience as a user of JPA, but the Hibernate team has years and years of supporting thousands and thousands of users. You should probably consider taking to our advice on what features are worth adding to JPA.

And it was pretty easy for me to find, with a quick Google search, examples of people trying to use `replace()` in JPQL. For example:

https://stackoverflow.com/questions/26266384/functions-and-operators-not-working-in-eclipselink
https://stackoverflow.com/questions/5634149/sql-replace-in-hql/42371466#42371466
https://stackoverflow.com/questions/6122560/hql-concat-function

(Note that you've always been able to use `replace()` in HQL, so there would be a lot more issues like this if HQL *didn't* support it.)

**Comment by m-reza-rahman** [comment]
With all due respect, I value all opinions including from end users and vendors (and strive to do so equally and fairly). Nonetheless, I believe my good faith opinion and perspective is worth stating and considering as well. The best decisions are not unilateral, no matter how valid any individual may think their perspectives are.

**Comment by gavinking** [comment]
With all due respect, I think you should defer to subject matter experts. In this case, the subject matter experts are people who're experts in JPA and persistence.

Sorry to break the news to you, but just as I'm not an expert on climate change, you're not an expert on persistence.

**Comment by gavinking** [comment]
To be clear: by opening this issue, I'm very much seeking feedback. Specifically, I'm hoping to receive technical objections, and feedback from other JPA implementors.

**Comment by m-reza-rahman** [comment]
I think this continues a pattern of needlessly abrasive, abusive and non-inclusive behavior that does not conform to the Eclipse Foundation Code of Conduct. I don’t think it is true that “expert opinions” automatically hold more weight. I believe this project and the Eclipse Foundation strives to value and respect all reasonable opinion stated in a reasonable fashion. Can you kindly comment @ivargrimstad? What are hu

**Comment by gavinking** [comment]
> I think this continues a pattern of needlessly abrasive, abusive and non-inclusive behavior

I think that's an utterly absurd allegation, and you should apologize to me.

**Comment by m-reza-rahman** [comment]
I am now reporting your behavior as a violation of the Eclipse Foundation Code of Conduct. The right folks can help us sort this out.

**Comment by gavinking** [comment]
LOL!

**Comment by gavinking** [comment]
So, my colleagues think that "LOL" wasn't the best response to you here, @m-reza-rahman. So let me give a proper response.

I have recently decided to come here and get involved, as a new contributor, certainly, but one with deep experience of JPA and persistence (I made fundamental contributions to the original JPA spec, and am also the creator of Hibernate, the leading implementation of JPA).

As a way of dipping my toe in the water, I opened a couple of very small issues, staying away, so I thought, from anything too controversial, and _volunteered my time to do the actual work on these things_.

Your response to two of the three tiny issues I opened was dismissive and unwelcoming, and you implicitly suggested (on the other thread) that you had a right to direct where community contributors should focus their voluntary contributions.

I suggested politely to you that "you should probably consider taking to our advice", given the depth of experience that we bring to the table, which you took as an insult. When I continued to politely disagree with you, you actually threatened to report me for a Code of Conduct issue!

This is not welcoming behavior, it's not respectful of volunteer contributors, and it's not the sort of behavior that is demanded by the Eclipse Code of Conduct. (Of course, I'm not going to report _your_ behavior.)

Nevertheless, I'm happy to move past this, because I think JPA is important, and I apologize for saying "LOL".

**Comment by m-reza-rahman** [comment]
I have always respected, continue to respect, and will always respect all contributions to any Jakarta EE specification from anyone and certainly yourself. I hope every single interaction of mine adequately reflects that spirit and intent. As I stated, I have already reported the behaviors in question. I am sure the right folks will consider all perspectives thoroughly and advise all of us accordingly.

As an aside, a warm welcome back to the specification.

**Comment by m0mus** [comment]
Folks, this conversation is inappropriate. You should respect each other opinion regardless of expertise levels. Please concentrate on technical topics. In case of disagreements ask other committers opinion, organize voting if needed. Although there is always an option to bring it to PMC if agreement cannot be reached, I believe that this issue can be solved within JPA project.

**Comment by gavinking** [comment]
> As I stated, I have already reported the behaviors in question.

Then you should of course withdraw that report, because it's an abuse of the process, and abusive/controlling towards me, being an attempt to punish me for disagreeing with you. And because it's a _terrible_ way to treat a new community member.

**Comment by m-reza-rahman** [comment]
Unfortunately I am unable to comply with your suggestion and would like the Code of Conduct reporting process to go through in due course. I am extremely sorry it had to come to this but I do believe that is the right thing to do in this context. It is especially saddening to me as I believe we have worked towards the same goals with honesty and passion for so many years now. This should not have happened.

**Comment by mmilinkov** [comment]
Just so there is no dangling references here. The Eclipse Foundation has looked into the code of conduct complaint raised by Reza. We believe that the matter has been resolved, and encourage all parties involved to get back to a collegial debate on the technical merits of these proposals. Thank you everyone for your contributions to Jakarta EE. They are very much appreciated by our community.

**Comment by beikov** [comment]
FWIW Hibernate 6.0 supports this at least in HQL. If anyone is willing to work on the spec parts, Hibernate can serve as a compatible implementation.
