### ISSUE TITLE
Add support for JSR303 (Bean validation) annotations.

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#34]
Right now, JPA spec neglect Bean Validation annotations.

The way it is now we end with duplicated information:

```
@Column(nullable = false, length = 200)
    @NotNull
    @Size(min = 4, max = 200)
    private String name;
```

Would be nice just do:

```
@Column
    @NotNull
    @Size(min = 4, max = 200)
    private String name;
```

and end with same result.

**Comment by m-reza-rahman** [comment]
I think the way things are right now is simple and allows for a clear separation of concerns. This proposal will find up being pretty convoluted. I suggest just closing this to reduce clutter.

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.

**Comment by gavinking** [comment]
> The way it is now we end with duplicated information:

Well, I can't speak for other JPA implementations, but at least in Hibernate this is *not* the case: DDL generation respects the Validation annotations, _as was always the intention of the people who write the Bean Validation spec._ @emmanuelbernard 

If there are other JPA implementations out there which *don't* respect the Bean Validation annotations in their DDL generation, then that's nothing more than a weakness in their implementation of DDL generation.

So this issue can surely be closed.

**Comment by gavinking** [comment]
Section 3.6 of the specification deals with Bean Validation integration.

The spec itself does not really tightly constrain DDL generation. (And this is a good thing IMO.) So whether any particular implementation respects Bean Validation annotations is a question for the implementation. In our implementation, we do take these annotations into account.
