### ISSUE TITLE
support for conditional index

### ISSUE THREAD

**Issue by carmi2214** [jakartaee/persistence#353]
Hi, I think it would be very useful to add in `Index.java` a property called `condition` / `where`, to use in DB types that support the feature. <br />

For example:

```java
@Target({})
@Retention(RUNTIME)
public @interface Index {

    /**
     * (Optional) The name of the index; defaults to a provider-generated name.
     */
    String name() default "";

    /**
     * (Required) The names of the columns to be included in the index, 
     * in order.
     */
    String columnList();

    /**
     * (Optional) Whether the index is unique.
     */
    boolean unique() default false;

    /**
     * (Optional) The contents of the where clause while creating the index.
     */
    String where() default "";

}
```

Useful for indicies on tables with logical deletion, or many other cases

**Comment by gavinking** [comment]
How many databases support this? Just Postgres and SQL Server?

**Comment by carmi2214** [comment]
> How many databases support this? Just Postgres and SQL Server?

Yep, those two and SQLite

**Comment by beikov** [comment]
It can be easily and safely emulated by transforming the index to a unique one I.e. `index on tbl1(col1) where col2 = 1` to `unique index on tbl1(col1, case when col2 = 2 then primaryKey else null end)` because nulls in unique indexes are ignored by default.

**Comment by gavinking** [comment]
Mmmmm. So look, every database has a _bunch_ of fancy proprietary options for creating indexes. We can't possibly expand the `@Index` annotation to accommodate all these things individually.

Now, perhaps it could make sense to add something like `indexDefinition` in analogy to `columnDefinition` in `@Column`, so you could write:

```java
@Index(name="orders_unbilled_index ", 
              columnList="order_nr", 
              indexDefinition ="where billed is not true")
```

To produce this DDL:

```sql
create index orders_unbilled_index on orders (order_nr)
    where billed is not true;
```

And of course you could also use it for lots of other things.

I guess that's kinda intellectually consistent at least.

On the other hand, you could just put that `create index` statement in a DDL script, and the JPA provider will happily execute the script for you, so the need is not really that acute, IMO.

Dunno.

**Comment by gavinking** [comment]
> It can be easily and safely emulated by transforming the index to a unique one

Ah, that's interesting.

**Comment by carmi2214** [comment]
> It can be easily and safely emulated by transforming the index to a unique one I.e. `index on tbl1(col1) where col2 = 1` to `unique index on tbl1(col1, case when col2 = 2 then primaryKey else null end)` because nulls in unique indexes are ignored by default.

Thank you for the suggestion, though still trying to add that option since it seems more like an elegant solution, for the relevant databases, IMO.

**Comment by carmi2214** [comment]
> Mmmmm. So look, every database has a _bunch_ of fancy proprietary options for creating indexes. We can't possibly expand the `@Index` annotation to accommodate all these things individually.

Looks awsome.
Would using it in ORM libraries be acceptable?

**Comment by gavinking** [comment]
@carmi2214 We need to pick just one of those alternatives. You can't have both 😅

**Comment by carmi2214** [comment]
Of course - excuse me, by "awsome" I meant to respond on the `indexDefinition` idea 😄

**Comment by gavinking** [comment]
Actually, since the `@ForeignKey` annotation defines a `foreignKeyDefinition` member which is supposed to specify the _whole_ DDL definition of the FK, instead of just some text to be appended at the end, we had better stay away from the use of "definition" here.

So perhaps what we should do is call it `options`:

```java
Index(name="orders_unbilled_index ", 
       columnList="order_nr", 
       options ="where billed is not true")
```

We could even add `options` members to other annotations like `@UniqueConstraint`, `@ForeignKey`, and even `@Table` and `@Column`.

I think this would be a quite useful enhancement.

**Comment by carmi2214** [comment]
Great! So, what's next?

**Comment by gavinking** [comment]
So your nagging worked: #485.

But now lets see what other people think.
