### ISSUE TITLE
Move this repo to https://github.com/jakartaee

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/persistence#376]
In the steering committee we voted to moved all specification projects from eclipse-ee4j to jakartaee. As such this repo should move to in due time.

Moving is fairly automatic, and redirects will be automatically put in place from the current location here to the new location.

If someone can authorise the move I can take care of it if needed.

Extra from: https://www.eclipse.org/lists/jakarta.ee-spec/msg02073.html

"We voted on it in 2019 and then in 2020 we added it explicitly to our 2021 plan and voted on that plan.  I think we just need to start executing.  I sent about 30 emails like the following in an attempt to add some shape to it and kick off the move in the spec projects. 

 - https://www.eclipse.org/lists/jakartaee-platform-dev/msg02940.html
 - https://www.eclipse.org/lists/messaging-dev/msg00028.html
 - https://www.eclipse.org/lists/jakartaee-tck-dev/msg01417.html
 - https://www.eclipse.org/lists/ejb-dev/msg00264.html
"

Also note that many projects have indeed moved: https://github.com/jakartaee/

**Comment by dmatej** [comment]
Yeah, it would be good to do that! :-)

**Comment by arjantijms** [comment]
Repo has been moved.

**Comment by lukasj** [comment]
Can you move also all remaining repos while you're at it?

**Comment by arjantijms** [comment]
> Can you move also all remaining repos while you're at it?

Working on it. There's still a small handful of repos to move indeed.

**Comment by lukasj** [comment]
thank you, that is helpful.
