### ISSUE TITLE
Clarify requirements on polymorphic associations

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#39]
The 2.0 specification states in 2.9 that "Relationships are polymorphic", but there exists one case that appears to be completely valid JPA that Hibernate explicitly does not support. The specification should explicitly state whether a provider is required to support this case.

When using a joined or single-table inheritance strategy, it is a common occurrence that an entity (e.g., <tt>Order</tt>) has a <tt>ManyToOne</tt> relationship with another entity (e.g., <tt>Customer</tt>). Since JPA supports class inheritance, it is possible that some of the <tt>Order</tt> instances are actually instances of a subclass (<tt>SpecialOrder</tt>), and we might want to have a <tt>Collection</tt> of just the <tt>SpecialOrder</tt> s on the <tt>Customer</tt> entity. (This is especially likely if <tt>Order</tt> is abstract and we want relationships directly to the subclasses.) An example class hierarchy looks like this:

```
@Entity
public class Customer {
  @OneToMany(mappedBy = "customer")
  private Set<SpecialOrder> specialOrders;

  @OneToMany(mappedBy = "customer")
  private Set<RegularOrder> regularOrders;
}

@Entity
public abstract class AbstractOrder {
  @ManyToOne
  private Customer customer;
}

@Entity
public class SpecialOrder extends AbstractOrder {
  private Date shippingDate;
}

@Entity
public class RegularOrder extends AbstractOrder {
  private Integer storeNumber;
}
```

The specification appears to imply but does not explicitly state that this arrangement is valid, while Hibernate explicitly requires that the <tt>mappedBy</tt> property be physically present on the exact class specified in the relationship mapping, not inherited from a superclass. This mismatch has inspired a surprising number of "how-to-work-around" blog posts and should be explicitly resolved for the next version of the specification.

**Comment by m-reza-rahman** [comment]
This looks like something that could be easily looked at and resolved. Perhaps it makes sense to triage this for consideration to be worked on during the next release? I would still mark this low priority.

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.

**Comment by gavinking** [comment]
> This looks like something that could be easily looked at and resolved. 

Actually I think this is pretty subtle. 

> I would still mark this low priority.

Right: I doubt it's a priority at all.

**Comment by gavinking** [comment]
This has now been fixed in Hibernate. I still don't think the spec needs to say anything about this issue.
