### ISSUE TITLE
add methods for managing Session/Transaction lifecycle to SessionFactory

### ISSUE THREAD

**Issue by gavinking** [jakartaee/persistence#410]
The transaction management idiom in JPA is not so trivial:

```java
var entityManager = factory.createEntityManager();
var transaction = entityManager.getTransaction();
try {
    transaction.begin();
    // do some work...
    transaction.commit();
}
catch (Exception e) {
    if (transaction.isActive()) {
        try {
            transaction.rollback();
        }
        catch (Exception x) {
            e.addSuppressed(x);
        }
   }
   throw e; 
}
finally {
    entityManager.close();
} 
```

I think we should add a `withTransaction()` method to `EntityManagerFactory` declared as follows:

```java
<R> R withTransaction(Function<EntityManager,R> work);
```

The `work` would be performed within the scope of a resource-local transaction.

**Comment by rbygrave** [comment]
I presume the alternative of using try-with-resources blocks is not workable?  Seems it could be done for EntityManager but problematic to get a transaction.close() in place?

**Comment by gavinking** [comment]
Folks, any feedback on https://github.com/jakartaee/persistence/pull/414?

One issue here is whether we need two flavors of `withTransaction()`, `void`, and one returning a value.

I think we _do_, but I don't know what to call them.

**Comment by gavinking** [comment]
@hantsy @Tomas-Kraus @lukasj and everyone else:

1. Are there any votes for renaming to `executeInTransaction()` + `computeInTransaction()`?
2. Alternatively, would anyone be in favor of just calling these methods `run()` and `call()` or `execute()` and `compute()`, and letting you pass in a `TxType.REQUIRED`, `TxType.REQUIRES_NEW`, etc.

So according to 2, you would write:

```java
entityManagerFactory.execute(TxType.REQUIRED, entityManager -> {
    entityManager.persist(book);
});
```

which is obviously quite a lot harder to type than:

```java
entityManagerFactory.executeInTransaction(entityManager -> {
    entityManager.persist(book);
});
```

But it's not _actually_ that much worse to look at, and it's quite a lot more flexible.

Another argument agains 2 is that the way `java.transaction` actually defines this enum is IMO pretty nasty:

- for some reason I cannot for the life of me understand, they defined the enum `TxType` as an inner type of the annotation type `@Transactional`, making it much less naturally-reusable, and
- `TxType` doesn't read well at all ... not to mention that it's not a "transaction type", but a transaction _propagation_ type.

We could of course define _our own_ `TransactionPropagationType` enum, perhaps justifiable on the basis that it's not just for JTA but also for resource-local transactions, but I would really prefer not to go there.

**Comment by lukasj** [comment]
For now, let's go without direct dependency on JTA API which would bring in CDI API (transitively)
