### ISSUE TITLE
EmbeddedId bad column ordering, and AttributeOverride does not have any effect on EmbeddedId

### ISSUE THREAD

**Issue by Guarmanda** [jakartaee/persistence#422]
An EmbeddedId in an entity creates the id columns at the END of the table, wich is very bad.
Adding AttributeOverride to an EmbeddedId will not have any effect, nor on the column name neither on the column ordering

```JAVA
@Embeddable
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
private static class SquadPersonneId {
    private Long idPersonne;
    private Long idSquad;
}

@EmbeddedId
@AttributeOverride(name = "idPersonne", column = @Column(name = "id_personne"))
@AttributeOverride(name = "idSquad", column = @Column(name = "id_squad", insertable = false, updatable = false))
private SquadPersonneId id;

//other columns
```
    
    
![image](https://github.com/jakartaee/persistence/assets/7463055/78bc664e-59cf-4896-b40d-2bed1af44dcf)

**Comment by gavinking** [comment]
This does not appear to be an issue with the JPA spec, which has nothing to say about column ordering, and seems to be about some specific implementation.

Is it fine if I close this?

**Comment by gavinking** [comment]
No response, so I'm closing. (Anyway it's simply not an issue for the spec.)
