### ISSUE TITLE
Use Named or Qualifier to replace the existing PersistenceContext/PersistenceUnit

### ISSUE THREAD

**Issue by hantsy** [jakartaee/persistence#456]
When switching to CDI first, #377, I would like deprecate the existing `PersistenceContext/PersistenceUnit` uses `@Named` or `@Qualifier` with `@Inject` instead.

```java
@Inject @Named("customerDatabase")  EntityManager em;
@Inject @CustomerDatabase  EntityManager em;

@Inject @CustomerDatabase  EntityManagerFactory emf;
```

`@Qualifier` is preferred, declaring an EMF with the same qualifiers, see #358

**Comment by gavinking** [comment]
Of course, if we address #377, that's the obvious thing to do. But look, we already have #377 and #309, I'm not sure we need to scatter the discussion across _three_ different issues.
