### ISSUE TITLE
custom value mappings for @Enumerated

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#47]
In mapping a pre-existing schema, it is rarely possible to map a given set of constants using an @Enumerated:

*   Ordinals are non-sequential
*   Names are incompatible with Java Enum Constants
*   Names cannot be aliased to something more useful or conventional for Java Naming standards

Limitation is because specification states the name() will be used of an enum.
A typical example: Database uses 'N/A', which can never be mapped to an enum. Intuition will let us look for a solution to map this to 'NOT_AVAILABLE', both a valid name for an Enum Constant, and also conventional naming.

On top of this, an enum often has a representation in the Database, and a constant has usually other additional attributes that could be useful.
Better than using the name() of an @Enumerated, we should map the enumerated similar as an @Entity, and use the @ID.

**Comment by gavinking** [comment]
So this very long discussion is quite old now, and doesn't seem to have ever reached much of a firm conclusion.
So let me give my take on this.

As pointed out by others, there's quite a lot of overlap with `AttributeConverter` here. _However_, there's one thing that `AttributeConverter`s aren't really set up to handle, and that's DDL generation. For a JPA `@Enumerated` field, we want to automatically generate a `check` constraint or a database-native `ENUM` type. To do that, we need to know upfront what values are possible.

So there's indeed a good case to me made for allowing explicit "remapping" of `enum` values.

Just off the top of my head, I can think of two ways to do this. The first is the one that seems to have been considered here:

```java
enum Status {
    OPEN, CLOSED, CANCELLED;

    @EnumeratedValue
    int toInt() {
        switch (this) {
            case OPEN: return 0;
            case CLOSED: return 1;
            case CANCELLED: return -1;
            default: throw new RuntimeException();
        }
    }
}
```

The problem with this is it makes the enumerated values implicitly dynamic. There's no way to force `toInt()` to return the same `int` value for a given enum value.

But there's a different way, which was mentioned in [this comment](https://github.com/jakartaee/persistence/issues/47#issuecomment-417722089):

```java
enum Status {
    @EnumeratedIntValue(0)
    OPEN, 
    @EnumeratedIntValue(1)
    CLOSED, 
    @EnumeratedIntValue(-1)
    CANCELLED;
}
```

That's shorter, and more "correct". It's the solution I've already proposed that we implement in Hibernate.

The downside to this approach is that we would need two annotations (`@EnumeratedIntValue` and `@EnumeratedStringValue` or whatever).

Anyway, I think the second approach would be thing worth having in JPA.

**Comment by gavinking** [comment]
> There's no way to force `toInt()` to return the same `int` value for a given enum value.

Well, excuse me, that was too wrong: actually @jaguild above already proposed to stick the annotation on a `final` _field_ of the `enum`, like this:

```java
enum Status {
    OPEN(0), CLOSED(1), CANCELLED(-1);

    @EnumeratedValue
    final int intValue;

    Status(int intValue) {
        this. intValue = intValue;
    }
}
```

And that works too. The advantage is that only one annotation is needed; the disadvantage is that I need to add a field to my `enum`. Not sure which is better.

**Comment by gavinking** [comment]
> And that works too.

In #463 I propose this solution. I've also reworked the section on `@Enumerated` to actually nail down what `STRING` and `ORDINAL` mean, since their semantics were left essentially undefined by the spec!
