### ISSUE TITLE
deprecate PersistenceUnitTransactionType

### ISSUE THREAD

**Issue by gavinking** [jakartaee/persistence#477]
After #465 we have the API `PersistenceTransactionType` and the SPI `PersistenceUnitTransactionType`.

We can deprecate `PersistenceUnitTransactionType` for removal.

**Comment by gavinking** [comment]
@lukasj Two questions:

1. should we add `EntityManagerFactory.getTransactionType()`?
2. should we rename this enum to the overly-verbose-but-more-precise `PersistenceTransactionManagementType`?

**Comment by gavinking** [comment]
Or just `PersistenceTransactionManagement`?

**Comment by hantsy** [comment]
`PersistenceTransactionType` is ok, but it seems txType attribute of `@Transactional()` is not a good naming, will confuse developers. The Spring `@Transactional` `propagation` is more reasonable.
