### ISSUE TITLE
@CurrentUser

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#48]
New annotation "@CurrentUser" should inject the current user into a data field (this is what databases do with the CURRENT USER constraint).

As in the Java EE environment there is a difference between security principals, business layer people, and database accounts, there should be a mapping available. For example "@CurrentUser(type = PRINCIPAL_NAME) String createdBy" would default the content of "createdBy" to the name of the caller principal's name. This is the most common need for automatic values in business applications.

**Comment by gavinking** [comment]
Nailing down the semantics of this thing seems like an almost impossible task. You have:

- the principal defined by the EE security layer,
- the database `current_user`,
- the tenant id in a multi-tenant database, and
- maybe even something else if you have a full-blown audit/historical data system.

Which of those things are we talking about here? How is there _any hope_ of reaching agreement on that?

I would say this doesn't belong in the spec.

**Comment by arjantijms** [comment]
I agree this doesn't belong in the current proposal in the Persistence spec. "@Inject Principal" for the EE Security layer is defined for all CDI beans, and if this one if needed something like a service or Entity listener classes can be injected with that and set it in the JPA entity.

**Comment by gavinking** [comment]
Yeah, injecting the `Principal` into an entity listener sounds like a fine solution for now.

And if/when we do #342 and #113, users could will be able to easily write their own `@CurrentUser` annotations that do exactly the thing they need in their programs.

I'm going to close this.
