### ISSUE TITLE
@QuerySingleResult

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#50]
New annotation "@QuerySingleResult(ejbql = "JPAQL QUERY" | namedQuery = "name of query")" should inject the .getSingleResult() output of either a given JPAQL query or of a named query into a field annotated with this annotation.

This is often needed in business applications, for example if the written data is dependend of a aggregate other entities. This is what a trigger would do in databases.

**Comment by gavinking** [comment]
I don't think this is a good idea, and I think we should just close this very old feature request.
