### ISSUE TITLE
Add accessor for PU name to EntityManagerFactory

### ISSUE THREAD

**Issue by gavinking** [jakartaee/persistence#503]
Every persistence unit has a well-defined name in JPA.

So it would make sense to let you access it via `EntityManagerFactory.getPersistenceUnitName()` or even just `EntityManagerFactory.getName()`.

This likely quite useful for generic (framework) code.

**Comment by dmatej** [comment]
It is useful especially for some types of tests when devs spend time by investigating a "magic" when they just could use `assertEquals("expectedPUName", em.getName());` to check they really work with the right entitymanager.
It could be useful also for logs.
