### ISSUE TITLE
consider deprecating CriteriaQuery.multiselect()

### ISSUE THREAD

**Issue by gavinking** [jakartaee/persistence#516]
The `multiselect()` method is not typesafe, so it's better to write:

    query.select(builder.array(book.get(Book_.title), book.get(Book_.isbn));

Than:

    query.multiselect(book.get(Book_.title), book.get(Book_.isbn));

Yeah, yeah, OK, so the second version saves some tokens in an already-verbose API.

But, I mean, _even so_, just look at the Javadoc of that method, which has to explicitly enumerate all the well-typed cases. That's a smell worse than volcanic hot springs.

So I would deprecate `CriteriaQuery.multiselect`, and point to `CriteriaBuulder.array` as the replacement. 

If you guys hate that idea, I would at least add some Javadoc warning users away from from `multiselect`, and pointing them to the alternative.

P.S. While we're here, I would suggest adding an overloads of `CriteriaBuilder.array()` and `CriteriaBuilder.tuple()` which accept `List` instead of varargs, similar to what we did in #137.

**Comment by dstutz** [comment]
Would like to add a little bit here in case anyone else ends up in the same boat as me.  I used `CriteriaQuery.multiselect` a lot to do DTO projections and for that use case where the generic type of the CriteriaQuery was, for example, BookInfo, I had to do:

`query.select(builder.construct(BookInfo.class, book.get(Book_.title), book.get(Book_.isbn)));`

**Comment by AB-xdev** [comment]
So after updating to Spring Boot 4.x we just stumbled over this deprecation.

After consulting a few colleagues we currently believe that this change offers no added values and just makes handling the API unnecessarily complex.

Consider the following code:

```java
var query = builder.createQuery(BookDTO.class)
query.multiselect(root.get(Book_.title), ...);
List<BookDTO> results = entityManager.createQuery(query).getResultList();
```

Using `#array` this would now look like this:

```java
var query = builder.createQuery(Object[]::new);
query.select(builder.array(root.get(Book_.title), ...);
List<BookDTO> results = entityManager.createQuery(query).getResultList()
    .stream()
    .map(oa -> new BookDTO((String)oa[0], ...))
    .toList();
```

or using `#tuple` it would look like that:

```java
var query = builder.createTupleQuery();
query.select(builder.tuple(root.get(Book_.title), ...);
List<BookDTO> results = entityManager.createQuery(query).getResultList()
    .stream()
    .map(t -> new BookDTO(t.get(0, Book_.title.getJavaType()), ...))
    .toList();
```

or using `#construct`:
```java
var query = builder.createQuery(BookDTO.class)
query.select(cb.construct(BookDTO.class, root.get(Book_.title), ...));
List<BookDTO> results = entityManager.createQuery(query).getResultList();
```

Our problems with the changes:
* Neither `#array` nor `#tuple` are fully type safe. `Object[]` and `Tuple` require doing explicit typing during selection and when creating the DTO. It's not enforced by the compiler that both mappings are identical and work.<br/>If for example `root.get(Book_.title)` is accidentally deleted in `#tuple` the code in `new BookDTO(t.get(0, Book_.title.getJavaType()), ...)` will still compile.
* `#construct` is exactly the same as `multiselect` but additionally requires a class type that is already known to the query. So this is just code duplication.
* We don't really understand reasoning behind `... just look at the Javadoc of that method, which has to explicitly enumerate all the well-typed cases.`

The current "fix" for this deprecation would be for us to rewrite the entire data access layer in dozens of projects.
I'm not sure where you guys are using JakartaEE but I'm talking about multiple hundred if not thousands of pieces of code that now require changes as most of our selects occur using DTOs.
This is not really sustainable for us and explainable in cost budgets - considering we have 0 advantages to show.

I would therefore recommend that this change is reverted.


The underlying problem that `multiselect` is not type safe could be addressed in different ways. For example by post processing the code (e.g. annotation processor) and checking if there is a matching constructor when calling `multiselect`.

**Comment by gavinking** [comment]
@AB-xdev You have misunderstood. Consider:

```java
var cb = factory.getCriteriaBuilder();

// compiles
var bookQuery1 = cb.createQuery(Book.class);
var from1 = bookQuery1.from(Book.class);
bookQuery1.multiselect(from1.get(Book_.text), from1.get(Book_.calendar));
List<Book> books1 = em.createQuery(bookQuery1).getResultList();

// does not compile
var bookQuery2 = cb.createQuery(Book.class);
var from2 = bookQuery2.from(Book.class);
bookQuery2.select(cb.array(from2.get(Book_.text), from2.get(Book_.calendar)));
List<Book> books2 = em.createQuery(bookQuery2).getResultList();
```

> I would therefore recommend that this change is reverted.

Not going to happen. This change already went into JPA 3.2, after *plenty* of opportunity for community review.

> The current "fix" for this deprecation would be for us to rewrite the entire data access layer in dozens of projects.

You do not have to rewrite your "entire data access layer" in order to change invocations of `multiselect(...)` to `multiselect(cb.array(...))`. You can just about do it with a regex.

Beside which, it's `@Deprecated`, not `@Deprecated(forRemoval=true)`. You don't have to do *anything*.

> I'm talking about multiple hundred if not thousands of pieces of code that now require changes as most of our selects occur using DTOs.

I think you will find that there exist tools and coding assistant which can help with tasks such as this one.

> For example by post processing the code (e.g. annotation processor) and checking if there is a matching constructor when calling multiselect.

This is not something that can be done in an annotation processor. A Java annotation processor cannot analyze expressions. (Except by casting to private comipiler APIs.)

**Comment by AB-xdev** [comment]
Thank you for the quick response.

> You have misunderstood. Consider: ...

We had a look at the code for a while and we don't really understand what you are trying to say with it.

```java
// does not compile
...
bookQuery2.select(cb.array(from2.get(Book_.text), from2.get(Book_.calendar)));
```

I know that this does not compile but therefore it's not a replacement. 

The Javadoc of `multiselect` also says

> Deprecated
> Since this method is not typesafe, the use of CriteriaBuilder.array or CriteriaBuilder.tuple with select is strongly preferred.

Could you please explain in more detail what your above code tries to say?


> Not going to happen. This change already went into JPA 3.2, after _plenty_ of opportunity for community review.

Sorry but you can't expect everyone to keep track of all developments in multiple hundred libraries that they use.
We had similar problems with other libraries in the past and usually managed to find a workable alternative without forking them.
I hope this will also be the case here.

> You do not have to rewrite your "entire data access layer" in order to change invocations of `multiselect(...)` to `multiselect(cb.array(...))`. You can just about do it with a regex.

Uhm, this is still using the deprecated API? I can't quite follow...

> Beside which, it's `@Deprecated`, not `@Deprecated(forRemoval=true)`. You don't have to do _anything_.

Let me explain:
A `Deprecation` annotation usually indicates that this API is getting removed sooner or later and causes a compiler/IDE warning.
<img width="580" height="99" alt="Image" src="https://github.com/user-attachments/assets/81f667e8-f6a3-4103-a417-71ff80083a67" />
It's kind of hard to spot other warnings when you have already a ton of "invalid" API deprecation warnings.
So we have to manually suppress them at each location and - in our case - this is a ton of locations.

**Comment by gavinking** [comment]
> We had a look at the code for a while and we don't really understand what you are trying to say with it.

I'm saying it's obviously wrong to be able to call `multiselect()` on a `Query<Book>`, since a `Query<Book>` produces a `List<Book>` when executed. It's doesn't produce a list of some compound type.

On the other hand, it's perfectly safe to call `select(array(...))`, since `array()` returns a `Selection<Object[]>`, and `select()` accepts a `Select<T>`.

If you don't understand what I'm saying then you'll just have to go away and think about it more carefully, since I don't have much time for this today.

> We had similar problems with other libraries in the past and usually managed to find a workable alternative without forking them.

Since this is *so* important to you, your best course of action is, as you suggest, to go ahead and fork the Jakarta Persistence API, because we're not going to roll back this deprecation. 

And that's the beauty of open source. Forking is totally allowed!

> A `Deprecation `annotation usually indicates that this API is getting removed sooner or later

That's not correct. Here's what the Javadoc for `@Deprecated` says about its purpose:

```
 * A program element annotated {@code @Deprecated} is one that programmers
 * are discouraged from using. An element may be deprecated for any of several
 * reasons, for example, its usage is likely to lead to errors; it may
 * be changed incompatibly or removed in a future version; it has been
 * superseded by a newer, usually preferable alternative; or it is obsolete.
```

In this case, "programmers are discouraged from using" the deprecated method because "its usage is likely to lead to errors".

HTH
