### ISSUE TITLE
Add variant of EntityManager#merge that modifies argument instead of returning new instance

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#55]
The <tt>EntityManager</tt>'s <tt>persist</tt> method modifies its argument (the entity to be persisted) with generated data such as the Id.

The <tt>merge</tt> method can also be used to persist a new entity, but has the additional benefit that it can also update the entity or any of its relations in the DB. <tt>merge</tt> however does not modify its argument but returns a new instance in which the generated data such as the Id is set.

For some uses cases its needed to have the original entity instance be modified such as the <tt>persist</tt> method does, but with the semantics of the <tt>merge</tt> method.

For instance, in a JSF application an existing (persistent but detached) entity is passed into an action method to add a new entity into e.g. a <tt>@OneToMany</tt> relation. When the action method returns, rendering of the page begins, which still has a reference to the original entity. Depending on the backing bean and template structure of the page in question, it might not be trivial to have the action method replace this original reference that was passed into it, and the kind of update that <tt>persist</tt> does would be **far** more convenient.

For this I would like to request adding a variant of <tt>EntityManager#merge</tt> that modifies its argument instead of returning a new instance.

Alternatively a <tt>refresh</tt> method that accepts detached entities could also work for the above mentioned use case. Yet another alternative might be having an <tt>attach</tt> method that makes its argument attached, overwriting fields in that argument if an entity with the same identity happened to be present in the persistence context, but contrary to <tt>merge</tt> not updating any data in the database.

**Comment by elab** [comment]
> ymajoros said:
What if you end up having multiple instances referring to the same row in database? They would all end up in PC??

Of course, no.  If there is a persistent instance with the same identifier, an exception should be thrown.
See semantics of Hibernate's `update()` method.

**Comment by elab** [comment]
Why still no progress here?
JPA is still missing "attach entity" functionality.
And internet is full of wrong diagrams pretending JPA can make a detached entity to managed.

Why not simply standardize what is done by Hibernate: `update()` and `saveOrUpdate()`?

**Comment by elab** [comment]
> ymajoros said:
> If you do this in JSF, you really need to use the returned entity. If you can't do that, you have an architecture problem anyway.

As explained above, it's more convenient if the object will be updated by JPA in-place.
Don't see an "architecture problem" here.

> persist() returns the same entity because it's new, and this guaranteed to be unique. You can't do that with updates.

`persist()` doesn't return anything. It updates the passed object (makes it managed) in-place.
We do want the same semantics for a merge() variant.

**Comment by gavinking** [comment]
Experience in the Hibernate community shows that the proposed operation (called `saveOrUpdate()` in Hibernate) leads to _many_ problems, and that's why we did not include it in JPA 1.0. This operation is now deprecated in Hibernate, and we should _definitely_ not add it to JPA.

**Comment by gavinking** [comment]
I'm going to close this issue, since it was already discussed to death by the JPA 1.0 expert group, and all parties agreed that this was something JPA should _not_ have.

**Comment by arjantijms** [comment]
@gavinking what about the following?

> Alternatively a refresh method that accepts detached entities could also work for the above mentioned use case.

**Comment by gavinking** [comment]
Well Hibernate's `refresh()` method used to do that, and it suffered from all of the exact same problems as `saveOrUpdate()`.

(Note that this is yet another case where a stateless `EntityManager` is useful.)

**Comment by gavinking** [comment]
The basic problem is that users just don't really have fine-grained control over what entities are already contained in the persistence context, and so unexpected errors are inevitable.

**Comment by gavinking** [comment]
I guess i really should re-emphasize what a complete *disaster* this feature was in the early days of Hibernate. Caused users endless hair-pulling.
