### ISSUE TITLE
@Convert annotation's converter property should be Class<? extends AttributeConverter>, not Class (unsafe)

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#56]
Currently, the <tt>converter</tt> property for the <tt>@Convert</tt> annotation is declared as follows:

```
Class converter() default void.class;
```

However, along with just generally being unsafe ("safe" use would be <tt>Class<?></tt>), this does not properly restrict the set of classes that can be specified. My understanding is that this MUST be a class that implements <tt>javax.persistence.AttributeConverter</tt>. Therefore, the <tt>converter</tt> property should be specified like so:

```
Class<? extends AttributeConverter> converter() default void.class;
```

With this change, the developer will know at compile time if he has specified an incorrect class. Without this change, the developer will not know until he gets a runtime error, which is seriously less desirable.

**Comment by gavinking** [comment]
Fixed in #487.
