### ISSUE TITLE
precision of SQL time and timestamp types

### ISSUE THREAD

**Issue by gavinking** [jakartaee/persistence#563]
JPA provides no way to specify the precision of SQL `time` and `timestamp` types (in fractional seconds).

For some time Hibernate has been abusing the `precision` member of the `@Column` annotation for this, but this has a bit of a problem in that its default value is `precision=0` [which is actually intended to be interpreted as `null`] and `0` is both (a) a meaningful/useful value, and (b) not the best default for a `timestamp`.

Therefore, I think we should formalize something in the JPA spec, by defining:

1. the default precision for a time (0 digits of fractional second precision, IMO)
2. the default precision for a timestamp (3-6 digits of fractional second precision, depending on the database, IMO)
3. a way for the user to explicitly specify the precision.

Now, there's three options I can think of for part 3:

- change the default of the `precision` member of the `@Column` to `-1`, so that the defaulted value can be interpreted based on the type,
- add a `fractionalSecondsPrecision` member to `@Column`, or
- introduce a new `@FractionalSeconds` annotation.

The disadvantage of the first option is it's in principle a breaking change.

**Comment by sebersole** [comment]
> introduce a new @FractionalSeconds annotation.

:+1:
