### ISSUE TITLE
EntityManagerFactory conflict error when upgrade to 3.2.0-M1

### ISSUE THREAD

**Issue by wwulfric** [jakartaee/persistence#569]
EntityManagerFactory interface [interface org.hibernate.SessionFactory] seems to conflict with Spring's EntityManagerFactoryInfo mixin - consider resetting the 'entityManagerFactoryInterface' property to plain [jakarta.persistence.EntityManagerFactory]
	at org.springframework.orm.jpa.Abstract

**Comment by gavinking** [comment]
This is the issue tracker for the Jakarta Persistence _specification_.

**Comment by stag33** [comment]
What's the solution for the above issue? I am stuck at this for a month

**Comment by gavinking** [comment]
The best solution to this problem is to stop using Spring and start using Jakarta EE instead.

**Comment by stag33** [comment]
It is difficult to quit spring as my entire architecture is based on spring boot MS. I am working on upgrading on one of the modules to spring boot 3.2.2 and JDK 17. Is there any alternate way to bypass this error?...like downgrading spring version or jakarta version?

**Comment by gavinking** [comment]
(For the record, you might possibly get a more helpful answer if you ask about your Spring problems in an issue tracker for Spring.)

**Comment by wwulfric** [comment]
> It is difficult to quit spring as my entire architecture is based on spring boot MS. I am working on upgrading on one of the modules to spring boot 3.2.2 and JDK 17. Is there any alternate way to bypass this error?...like downgrading spring version or jakarta version?

springboot 3.2.1, spring-data-bom 2023.1.2, jakarta.persistence-api 3.1.0 works for me

**Comment by stag33** [comment]
Hi @wwulfric, tried with above versions, but didnt work for me. Can you share your github repository link or code where you faced this error?

**Comment by wwulfric** [comment]
@stag33 sorry but this repository is internal to the company; I can't make it open source.

**Comment by stag33** [comment]
@wwulfric, same case for me, my repository is also internal, if you used spring-data-bom, did you remove spring-data-jpa from pom.xml?

**Comment by wwulfric** [comment]
@stag33 yes. spring-data-jpa'version is 3.2.2 and spring orm 6.1.2

**Comment by stag33** [comment]
I did not understand your last statement, Were you using spring-data-jpa and spring-data-bom at the same time?

**Comment by wwulfric** [comment]
spring-data-jpa is introduced by spring-data-bom（https://www.baeldung.com/spring-maven-bom）
