### ISSUE TITLE
Wrong query result type in TCK tests

### ISSUE THREAD

**Issue by beikov** [jakartaee/persistence#579]
The following two tests use wrong query result types:
* `com/sun/ts/tests/jpa/core/criteriaapi/From/Client.java#fromGetMapAttributeTest`
* `com/sun/ts/tests/jpa/core/criteriaapi/From/Client.java#pathGetMapAttributeTest`

They construct a `CriteriaQuery` with the result type `jakarta.persistence.criteria.Expression` but select an `Employee` which is obviously incompatible. Hibernate ORM recently introduced a type assignability validation which now causes an error when executing these TCK tests.

The two tests should be excluded for now and fixed in the next TCK version.

**Comment by scottmarlow** [comment]
@lukasj do you want to manage this here as a Persistence TCK challenge (needs challenge label) that if accepted, the described tests will be excluded from the Jakarta EE 10 Platform TCK + Persistence 3.1 TCK (e.g. https://download.eclipse.org/jakartaee/persistence/3.1)?

Thanks!

**Comment by lukasj** [comment]
challenge accepted

...I mean labels added to avoid any confusions :-)

**Comment by scottmarlow** [comment]
@beikov since this is approved, I'll merge your change to the https://github.com/jakartaee/platform-tck/tree/tckrefactor (for EE 11 currently) and https://github.com/jakartaee/platform-tck/tree/10.0.x branches (for EE 10) Platform TCK branches where we generate the Persistence TCK from.

**Comment by scottmarlow** [comment]
https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-standalonetck-build-run-100/117 generated the staged Persistence https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-persistence-tck-3.1.3.zip which includes the https://github.com/jakartaee/platform-tck/pull/1246 change.

https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-standalonetck-build-run-100/117/testReport/ shows that the staged Persistence TCK 3.1.3 TCK passed all tests with GlassFish which includes EclipseLink.

CC @beikov

**Comment by scottmarlow** [comment]
I think that this issue can be closed now

**Comment by lukasj** [comment]
per the last comment
