### ISSUE TITLE
Clarify namespaces of type aliases and named parameters

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#59]
JPA 2.1 Section 3.10.12, "Named Parameters", does not explicitly require that the namespaces of type aliases and named parameters be distinct. Some implementations fail & some succeed on JPQL of the following form:
SELECT x FROM Thing x WHERE x.foobar = :x

The specification should be explicit as to whether type aliases and named parameters share the same namespace.
#### Environment
JPA 2.1

**Comment by m-reza-rahman** [comment]
This seems like low-hanging fruit that could be looked at in the next release and resolved one way or the other? It does appear to be a fairly low priority either way.

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.

**Comment by gavinking** [comment]
> Some implementations fail & some succeed on JPQL of the following form:
>
>     SELECT x FROM Thing x WHERE x.foobar = :x

This just sounds like a bug in one particular product.

I don't think there's _any_ reason to imagine that identification variables (not "type aliases") and named parameters share a namespace, and so I don't think there's anything that needs fixing here.

We should close this, IMO.

**Comment by gavinking** [comment]
This is issue is slightly more than a decade old and has no votes. Closing.
