### ISSUE TITLE
Retrieving primary key of lazy relationship

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#61]
My server passes entities to clients as XML representations, simply by marshalling it using JAXB. This works well but there is one case where it fails: LAZY relationships. As I just want to include a URL for each reference (so clients can decide on their own whether to load this in turn), I need access to the primary key. But, as it is a LAZY reference, the attribute itself is NULL, and if I use the getter(), then the complete entity is instantiated – which I do not need and do not want. So it would be really great, if there would be solution, which makes JAXB and JPA work more closely. Like an API to get the primary keys of LAZY relationships, or even better, an automatic integration. ![](https://java.net/jira/images/icons/emoticons/smile.gif)
#### Environment
JPA 2.0

**Comment by gavinking** [comment]
This is already possible since JPA 2.0 via `PersistenceUnitUtil.getIdentifier()`.
