### ISSUE TITLE
MapKeyColumn misses secondPrecision member

### ISSUE THREAD

**Issue by beikov** [jakartaee/persistence#615]
`Column` received a new member `secondPrecision`, but apparently it was forgotten on `MapKeyColumn`. Would be nice to align that and also in the XML.

**Comment by gavinking** [comment]
i.e. map keys should always be _discrete_ types: enums, string, integers, etc.

**Comment by beikov** [comment]
I guess that's also why you deprecated the `MapKeyTemporal` annotation? I don't have a strong opinion, and I understand that mapping temporals as map key is probably not very common, but I don't see a fundamental problem. Temporals are exact, not like approximate numerics. Anyway, I don't want to start a discussion. Merely wanted to point out this situation because of a Hibernate ORM 7 exception caused by the lack of this member.

**Comment by gavinking** [comment]
> I guess that's also why you deprecated the `MapKeyTemporal` annotation? 

No, that's because we also deprecated `@Temporal`. Use of `java.sql` types is deprecated in JPA 3.2.
