### ISSUE TITLE
Compatibility certification request for Hibernate 7.0.0.Alpha2

### ISSUE THREAD

**Issue by sebersole** [jakartaee/persistence#623]
* [x]  Organization Name ("Organization") and, if applicable, URL
  Red Hat, Inc
* [x]  Product Name, Version and download URL (if applicable)
  [Hibernate 7.0.0.Alpha2](https://hibernate.org/orm/releases/7.0/)
* [x]  Specification Name, Version and download URL
  [Jakarta Persistence 3.2](https://jakarta.ee/specifications/persistence/3.2)
* [x]  TCK Version, digital SHA-256 fingerprint and download URL
  [Jakarta Persistence TCK 3.2.0](https://download.eclipse.org/jakartaee/persistence/3.2/jakarta-persistence-tck-3.2.0.zip), SHA=db74101c3f52f737f57804271ea9c845cb1941f2a0685284c54c4ad4fa1f05c7
* [x]   Public URL of TCK Results Summary
  [Results with Java 17](https://ci.hibernate.org/view/ORM/job/hibernate-orm-tck-3.2/job/wip%252F7.0/24/artifact/results/test-reports/failsafe-report.html)
  [Results with Java 21](https://ci.hibernate.org/view/ORM/job/hibernate-orm-tck-3.2/job/wip%252F7.0/25/artifact/results/test-reports/failsafe-report.html)
* [x]  Any Additional Specification Certification Requirements
  None
* [x]  Java runtime used to run the implementation
  Temurin JDK 17.0.11+9
  Temurin JDK 21.0.3+9
* [x]  Summary of the information for the certification environment, operating system, cloud, ...
  Apache Derby 10.15.2.0, Linux
* [x]  By checking this box I acknowledge that the Organization I represent accepts the terms of the EFTL.
* [x]  By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
@sebersole Two things:

1.  Can you verify the SHA of the TCK zip?  The one used for EclipseLink as well as the one I got from sha256sum of the one staged by the project is

`db74101c3f52f737f57804271ea9c845cb1941f2a0685284c54c4ad4fa1f05c7`

2. Please also link directly to the results of the TCK runs so they are easier to find for the reviewers
- https://ci.hibernate.org/view/ORM/job/hibernate-orm-tck-3.2/job/wip%252F7.0/24/artifact/results/test-reports/failsafe-report.html
- https://ci.hibernate.org/view/ORM/job/hibernate-orm-tck-3.2/job/wip%252F7.0/25/artifact/results/test-reports/failsafe-report.html

**Comment by lukasj** [comment]
accepted
