### ISSUE TITLE
confused about the path expression

### ISSUE THREAD

**Issue by codeleeks** [jakartaee/persistence#643]
here's codes i want to clarify.

```java
    public List<Order> findAllWithItem() {
       //this jpql works fine!
      String jpql = "select distinct o from Order o join fetch o.member m join fetch o.delivery d join fetch o.orderItems join fetch o.orderItems.item i";
        return em.createQuery(jpql, Order.class)
                 .getResultList();
    }
```

a collection field is not able to navigate to any related field. it is a terminated value.

here's official docs about that.
![image](https://github.com/user-attachments/assets/a94f6cd9-007a-45b3-bc25-0bd0566e05d1)
(https://docs.oracle.com/javaee/7/tutorial/persistence-querylanguage005.htm#BNBUQ:~:text=For%20example%2C%20the%20expression%20p.teams.league.sport%20is%20illegal%20because%20teams%20is%20a%20collection%2Dvalued%20relationship%20field)

but it seems like it could navigate to related field in the join fetching expressions(` join fetch o.orderItems.item i` )

it works as expected when i remove `join fetch o.orderItems` from the jpql.

```java
    public List<Order> findAllWithItem() {
        //it won't work with error (org.hibernate.query.SemanticException: Query specified join fetching, but the owner of the fetched association was not present in the select list)
        String jpql = "select distinct o from Order o join fetch o.member m join fetch o.delivery d join fetch o.orderItems.item i";
        return em.createQuery(jpql, Order.class)
                 .getResultList();
    }
```

so, my question is
when does JPA allow collections to navigate to related field exactly or not?

**Comment by gavinking** [comment]
This is the issue tracker for the Persistence specification, not for whatever implementation (EclipseLink, I suppose) that documentation refers to. You should direct your question to EclipseLink folks.
