### ISSUE TITLE
update and/or validate javax.persistence.schema-generation.database.action

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#68]
I think that an "update" and a "validate" schema-generation.database.action might come in handy, especially for production environments where Java EE 7 will be running in the comming future.

Of course you don't want your database to be accidentally being removed if you still have the "create-drop" enabled, and a new action won't solve that.
But without the "update" action you still have to resort to solutions like Google Flyway or DbMaintain to update an existing database schema.

Are there plans to incorporate a new action like "update" or "validate", the way Hibernate supports it?
Or are they left out by design?

**Comment by gavinking** [comment]
We will probably add a `validate` setting as part of the work on #399. We probably won't add `update`, since it's just never very robust.
