### ISSUE TITLE
Add subquery(EntityType) to javax.persistence.criteria.CriteriaQuery

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#71]
If using dynamic entities not defined by classes (as is the case when using EntityMode.MAP), there's no way to create a subquery. This is because javax.persistence.criteria.CriteriaQuery.subquery() takes an entity Class as an argument, and unlike javax.persistence.criteria.CriteriaQuery.from() there's no overloaded method to subquery by EntityType. This severely limits what can be done using entities mapped with EntityType for which there is no Java class.

**Comment by gavinking** [comment]
This is a perfectly sensible and straightforward request. 

I've added the missing overload to `CommonAbstractCriteria` in #71.

**Comment by lukasj** [comment]
done in #467
