### ISSUE TITLE
Obtaining @Version value

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#74]
I want to suggest that a future release of the JPA API provides a means to get the value of an entities version attribute.

Example: em.getVersion(myEntity);
he
Justification: Generic frameworks like JAX-RS or Servlets might have an interest in getting the value of the version attribute without "knowing" which is "the version attribute" for any particular entity. For example, JAX-RS or Servlets want to send a ETag header to a client for _any_ entity, but the Servlet does not "know" the class of that entity. Like when class name and primary key value are provided by a HTTP request. In that case, a solution would be em.getVersion(myEntity) which just should return the value of the version.

**Comment by kalgon** [comment]
Shouldn't a `getVersion(entity)` method be added to the `PersistenceUnitUtil` class where there's already a `getIdentifier(entity)` method?

**Comment by gavinking** [comment]
This is a reasonable-enough request, and there's been some low-level activity on this issue, so check out #451.
