### ISSUE TITLE
Allow specification for null handling in order-by expressions (JPQL and Criteria API)

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#76]
§4.9 of the specification explictly states:

> SQL rules for the ordering of null values apply: that is, all null values must appear before all non-null values in the ordering or all null values must appear after all non-null values in the ordering, but it is not specified which.

However, pretty much all of the important JPA providers support a <tt>nulls first</tt>/<tt>nulls last</tt> clause. So while it is already possible to define the strategy, it would be cool if one could reliably use it on top of JPA.

**Comment by odrotbohm** [comment]
Is there a chance, this get's prioritized for JakartaEE 10? Users of Spring Data JPA and downstream projects have been repeatedly and patiently asked for this for years, and it's a severe limitation compared to accessing other store types.

**Comment by beikov** [comment]
If anyone is willing to work on this, Hibernate can serve as a compatible implementation.

**Comment by opengeekv2** [comment]
How hard would it be to take this on as a new (and ocasional) contributor?

**Comment by gavinking** [comment]
I have proposed a solution in #440.
