### ISSUE TITLE
@Version Support for Temporal Types

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#81]
The JPA 2.1 specification currently indicates that <tt>Timestamp</tt> is the only supported temporal type for <tt>@Version</tt> properties:

> The following types are supported for version properties: <tt>int, Integer, short, Short, long, Long, Timestamp</tt>.

I'd propose that additional temporal types are supported as well:

<tt>java.util.Date, java.util.Calendar, java.sql.Date, java.sql.Time, java.sql.Timestamp</tt>

**Comment by andyjefferson** [comment]
FWIW java.time.Instant would be a much more useful addition here.

**Comment by gavinking** [comment]
In #450 I propose adding `LocaDateTime` and `Instant`. We don't need to add the other date/time types mentioned above, since they're being deprecated.
